apiVersion: operators.coreos.com/v1alpha2
kind: OperatorGroup
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "230"
  name: operatorgroup
  namespace: cp4ba
spec:
  targetNamespaces:
  - cp4ba