apiVersion: operators.coreos.com/v1alpha2
kind: OperatorGroup
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '230'
  labels:
    argo.cntk/instance: ibm-cp4ba-operator
  name: operatorgroup
  namespace: ibm-common-services
spec:
  targetNamespaces:
    - ibm-common-services