apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "240"
  name: ibm-cp4ba-operator-catalog-subscription
  namespace: cp4ba
spec:
  channel: v21.0.1
  name: ibm-cp4ba-operator
  installPlanApproval: Automatic
  source: ibm-operator-catalog
  sourceNamespace: openshift-marketplace
